#!/usr/bin/bash
chmod a+x $HOME/ros_ws/src/bluetooth_bridge/src/bluetooth_bridge_server_node.py
chmod a+x $HOME/ros_ws/src/bluetooth_bridge/src/serial_port_server_node.py
chmod a+x $HOME/ros_ws/src/bluetooth_bridge/src/sound_server_node.py
roslaunch bluetooth_bridge bluetooth_bridge.launch
